# Homework 3
## OCNG-489
### Author: Trenton W. Spencer
### Python 3.5.1

In [97]:
import numpy as np

In [98]:
#Question 1
vec1 = np.zeros(10)
vec1[4] = 1
vec1

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [99]:
#Question 2
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [100]:
#Question 3
def reverse(x):
    '''Reverses the vector order, so that the last element in the vector becomes the first.'''
    return x[::-1]
    
y = np.array([0,1,2,3])
reverse(y)

array([3, 2, 1, 0])

In [101]:
#Question 4
def find_nonzero(z):
    '''Returns the non-zero numbers of an array'''
    l = []
    for num in z:
        if num != 0:
            l.append(num)
    return np.array(l)

find_nonzero([1,2,0,0,4,0])

array([1, 2, 4])

In [102]:
#Question 5
a = np.random.normal(loc = 0, scale = 1, size = (1,3,3))
print(a)
a[0,:,1]

[[[ 0.60662973  1.116576    0.2806891 ]
  [-0.24378996  0.89757317 -0.30035777]
  [ 0.68826144 -0.32071536 -0.14464123]]]


array([ 1.116576  ,  0.89757317, -0.32071536])

In [103]:
#Question 6
randarr = np.random.rand(10,10)
mn = np.min(randarr[1,:])
mx = np.max(randarr[:,3])
print('The minimum value of the 2nd row is: ', mn, '\n The maximum value of the 4th column is: ', mx)

The minimum value of the 2nd row is:  0.218859305831 
 The maximum value of the 4th column is:  0.918770218992


In [104]:
#Question 7
np.linspace(0,10,num = 11, endpoint = False)[1:]

array([ 0.90909091,  1.81818182,  2.72727273,  3.63636364,  4.54545455,
        5.45454545,  6.36363636,  7.27272727,  8.18181818,  9.09090909])

In [105]:
#Question 8
randoarr = np.random.random(10)
randoarr.sort()
randoarr

array([ 0.10815073,  0.17615307,  0.22503961,  0.33245453,  0.66025911,
        0.69437738,  0.71005041,  0.76065153,  0.79345138,  0.87123393])

In [134]:
#Question 9
def is_equal(A,B):
    if (A == B).all():
        return True
    else:
        return False
    
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,20]])
is_equal(A,B)

False

In [107]:
#Question 10
mat = np.matrix([[10,15,20],[6,36,1296],[4,64,12]])
mat[0] = mat[0] - np.mean(mat[0])
mat[1] = mat[1] - np.mean(mat[1])
mat[2] = mat[2] - np.mean(mat[2])
mat

matrix([[  -5,    0,    5],
        [-440, -410,  850],
        [ -22,   37,  -14]])

In [155]:
#Question 11a
array1 = np.random.rand(5, 5, 3)
array2 = np.random.rand(5, 5)
array2 = array2[:,:,np.newaxis]
array1 * array2

array([[[ 0.62969761,  0.2719687 ,  0.26009219],
        [ 0.70855785,  0.48687742,  0.50652135],
        [ 0.00686611,  0.01255973,  0.01290911],
        [ 0.13961793,  0.43558875,  0.13292337],
        [ 0.44668966,  0.34673889,  0.06635398]],

       [[ 0.01362762,  0.04434517,  0.02619089],
        [ 0.39236208,  0.27505437,  0.21835198],
        [ 0.00757436,  0.06875872,  0.00870662],
        [ 0.35487041,  0.24705343,  0.02865179],
        [ 0.28453637,  0.6075058 ,  0.13290243]],

       [[ 0.22927914,  0.13178649,  0.31492284],
        [ 0.32682382,  0.20952825,  0.20301224],
        [ 0.13330048,  0.36246752,  0.06215521],
        [ 0.11412591,  0.14280585,  0.18180759],
        [ 0.74058632,  0.67099452,  0.7265713 ]],

       [[ 0.04148672,  0.21295337,  0.12040207],
        [ 0.24721761,  0.08337228,  0.08963042],
        [ 0.51323841,  0.27851564,  0.39711545],
        [ 0.09675475,  0.05492514,  0.0755781 ],
        [ 0.37591189,  0.08754619,  0.30249855]],

       [[ 0.

In [154]:
#Question 11b
array1 = np.random.rand(3, 5, 5)
array2 = np.random.rand(5, 5)
array2 = array2[np.newaxis,:,:]
array1 * array2

array([[[  1.82391896e-01,   2.68464054e-01,   9.18536064e-02,
           1.41862367e-01,   1.85304477e-01],
        [  3.39081724e-01,   7.18630912e-02,   1.53712549e-01,
           1.84245962e-01,   3.39835651e-01],
        [  1.87858373e-02,   1.42918670e-01,   4.53001919e-01,
           5.14981183e-03,   3.26502231e-01],
        [  4.71114452e-01,   3.14334864e-02,   7.42714037e-03,
           2.73332795e-01,   4.21220559e-01],
        [  4.69623765e-01,   8.83284401e-02,   4.59381875e-01,
           5.91829957e-04,   3.52508344e-01]],

       [[  2.39966451e-03,   3.39408261e-01,   1.40441408e-01,
           2.69947430e-01,   1.48238731e-01],
        [  2.99808217e-01,   7.31852555e-02,   2.43706200e-01,
           3.07034358e-01,   5.17274650e-01],
        [  5.49760005e-02,   9.81831615e-03,   7.15115000e-01,
           1.37648292e-01,   3.83782044e-01],
        [  5.40073730e-01,   4.51031360e-01,   1.26354268e-02,
           3.65132303e-01,   1.82220236e-01],
        [  8.7315

In [135]:
#Question 12
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
r = []
for i in range(0,11):
    s = Z[i:i+4]
    r.append(s)
np.array(r)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [136]:
#Question 13
def cart2polar(xy):
    conv = []
    for k in range(len(xy)):
        x = xy[k,0]
        y = xy[k,1]
        r = np.sqrt(x**2 + y**2)
        theta = np.arctan(y/x)
        conv.append([r, theta])
    return np.array(conv)

ex = np.array([[1,2],[3,3],[6,9]])
cart2polar(ex)

array([[  2.23606798,   1.10714872],
       [  4.24264069,   0.78539816],
       [ 10.81665383,   0.98279372]])

In [156]:
#Question 14
%time
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
%timeit sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 21.2 µs
The slowest run took 27.55 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.4 µs per loop


In [123]:
#Question 15
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    a[:2, :] = a[:2,:] - (a[:2,:]/4)
    b = b[:,np.newaxis]
    return a*b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

#The way it was written just confused me, so I rewrote it as a single line. Had to create new dimension for b
#to be multiplied out.

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

In [110]:
#Question 16
data = np.loadtxt('../python4geosciences/data/burl1h2010.txt', comments = '#')
vdir = data[:,5]
vspd = data[:,6]
def uvconvert(vdir,vspd):
    components = []
    u = vspd*np.cos(np.deg2rad((vdir - 180)))
    v = vspd*np.sin(np.deg2rad((vdir - 180)))
    components.append([u,v])
    return np.transpose(np.array(components))

uvconvert(vdir, vspd)

array([[[  2.08397511],
        [ -2.1580194 ]],

       [[  1.96070053],
        [ -3.01921404]],

       [[  2.12119911],
        [ -2.52794666]],

       ..., 
       [[  9.56084447],
        [ -6.208885  ]],

       [[ 10.50707636],
        [ -5.5867116 ]],

       [[  8.83345912],
        [ -5.1       ]]])